<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('submittals', function (Blueprint $table) {
            $table->dropColumn('name');
            $table->string('transactionName')->nullable();
            $table->string('additionalEmail')->nullable();
            $table->string('agentName')->nullable();
            $table->string('commingSoon')->nullable();
            $table->date('comingSoonDate')->nullable();
            $table->string('tmName')->nullable();
            $table->date('activeDate')->nullable();
            $table->string('agreementExecuted')->nullable();
            $table->decimal('price', 10, 2)->nullable();
            $table->date('photoDate')->nullable();
            $table->string('photoURL')->nullable();
            $table->string('bedsBathsTotal')->nullable();
            $table->string('tourURL')->nullable();
            $table->string('usingCHR')->nullable();
            $table->string('needOE')->nullable();
            $table->string('hasHOA')->nullable();
            $table->string('includeInsights')->nullable();
            $table->string('titleToOrderHOA')->nullable();
            $table->string('mailoutNeeded')->nullable();
            $table->string('powerOfAttnyNeeded')->nullable();
            $table->string('hoaName')->nullable();
            $table->string('hoaPhone')->nullable();
            $table->string('hoaWebsite')->nullable();
            $table->text('miscNotes')->nullable();
            $table->string('scheduleSignInstall')->nullable();
            $table->string('conciergeListing')->nullable();
            $table->string('signInstallVendor')->nullable();
            $table->text('draftShowingInstructions')->nullable();
            $table->string('titleCompany')->nullable();
            $table->string('closerNamePhone')->nullable();
            $table->string('signInstallVendorOther')->nullable();
            $table->date('signInstallDate')->nullable();
            $table->string('reColorado')->nullable();
            $table->string('navica')->nullable();
            $table->string('ppar')->nullable();
            $table->string('grandCounty')->nullable();
            $table->string('ires')->nullable();
            $table->text('mlsPrivateRemarks')->nullable();
            $table->text('mlsPublicRemarks')->nullable();
            $table->string('feesCharged')->nullable();
            $table->string('referralToPay')->nullable();
            $table->decimal('amountToCHR', 10, 2)->nullable();
            $table->text('referralDetails')->nullable();
            $table->string('matterport')->nullable();
            $table->string('floorPlans')->nullable();
            $table->string('threeDZillowTour')->nullable();
            $table->string('onsiteVideo')->nullable();
            $table->string('propertyWebsite')->nullable();
            $table->string('emailBlastSphere')->nullable();
            $table->string('emailBlastReverseProspect')->nullable();
            $table->string('propertyHighlightVideo')->nullable();
            $table->string('socialMediaImages')->nullable();
            $table->string('socialMediaAds')->nullable();
            $table->string('priceImprovementPackage')->nullable();
            $table->string('customDomainName')->nullable();
            $table->text('featuresNeededForVideo')->nullable();
            $table->text('marketingNotes')->nullable();
            $table->string('brochureLine')->nullable();
            $table->string('brochurePrint')->nullable();
            $table->text('bullets')->nullable();
            $table->string('headlineForBrochure')->nullable();
            $table->string('stickyDots')->nullable();
            $table->string('qrCodeSheet')->nullable();
            $table->string('qrCodeSignRider')->nullable();
            $table->string('featureCards')->nullable();
            $table->string('featureCardCopy')->nullable();
            $table->date('brochureDeliveryDate')->nullable();
            $table->string('deliveryAddress')->nullable();
            $table->date('printedItemsPickupDate')->nullable();
            $table->date('brochurePickupDate')->nullable();
            $table->string('isSubmittalComplete')->nullable();
            $table->string('submittalName')->nullable();
            $table->string('submittalType')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('submittals', function (Blueprint $table) {
            $table->dropColumn([
                'transactionName',
                'additionalEmail',
                'agentName',
                'commingSoon',
                'comingSoonDate',
                'tmName',
                'activeDate',
                'agreementExecuted',
                'price',
                'photoDate',
                'photoURL',
                'bedsBathsTotal',
                'tourURL',
                'usingCHR',
                'needOE',
                'hasHOA',
                'includeInsights',
                'titleToOrderHOA',
                'mailoutNeeded',
                'powerOfAttnyNeeded',
                'hoaName',
                'hoaPhone',
                'hoaWebsite',
                'miscNotes',
                'scheduleSignInstall',
                'conciergeListing',
                'signInstallVendor',
                'draftShowingInstructions',
                'titleCompany',
                'closerNamePhone',
                'signInstallVendorOther',
                'signInstallDate',
                'reColorado',
                'navica',
                'ppar',
                'grandCounty',
                'ires',
                'mlsPrivateRemarks',
                'mlsPublicRemarks',
                'feesCharged',
                'referralToPay',
                'amountToCHR',
                'referralDetails',
                'matterport',
                'floorPlans',
                'threeDZillowTour',
                'onsiteVideo',
                'propertyWebsite',
                'emailBlastSphere',
                'emailBlastReverseProspect',
                'propertyHighlightVideo',
                'socialMediaImages',
                'socialMediaAds',
                'priceImprovementPackage',
                'customDomainName',
                'featuresNeededForVideo',
                'marketingNotes',
                'brochureLine',
                'brochurePrint',
                'bullets',
                'headlineForBrochure',
                'stickyDots',
                'qrCodeSheet',
                'qrCodeSignRider',
                'featureCards',
                'featureCardCopy',
                'brochureDeliveryDate',
                'deliveryAddress',
                'printedItemsPickupDate',
                'brochurePickupDate',
                'isSubmittalComplete',
                'submittalName',
                'submittalType',
            ]);
        });
    }
};