<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('submittals', function (Blueprint $table) {
            $table->dropColumn('name');
            $table->string('transactionName')->nullable();
            $table->string('additionalEmail')->nullable();
            $table->string('agentName')->nullable();
            $table->boolean('commingSoon')->default(false);
            $table->date('comingSoonDate')->nullable();
            $table->string('tmName')->nullable();
            $table->date('activeDate')->nullable();
            $table->boolean('agreementExecuted')->default(false);
            $table->decimal('price', 10, 2)->nullable();
            $table->date('photoDate')->nullable();
            $table->string('photoURL')->nullable();
            $table->string('bedsBathsTotal')->nullable();
            $table->string('tourURL')->nullable();
            $table->boolean('usingCHR')->default(false);
            $table->boolean('needOE')->default(false);
            $table->boolean('hasHOA')->default(false);
            $table->boolean('includeInsights')->default(false);
            $table->boolean('titleToOrderHOA')->default(false);
            $table->boolean('mailoutNeeded')->default(false);
            $table->boolean('powerOfAttnyNeeded')->default(false);
            $table->string('hoaName')->nullable();
            $table->string('hoaPhone')->nullable();
            $table->string('hoaWebsite')->nullable();
            $table->text('miscNotes')->nullable();
            $table->boolean('scheduleSignInstall')->default(false);
            $table->boolean('conciergeListing')->default(false);
            $table->string('signInstallVendor')->nullable();
            $table->text('draftShowingInstructions')->nullable();
            $table->string('titleCompany')->nullable();
            $table->string('closerNamePhone')->nullable();
            $table->string('signInstallVendorOther')->nullable();
            $table->date('signInstallDate')->nullable();
            $table->boolean('reColorado')->default(false);
            $table->boolean('navica')->default(false);
            $table->boolean('ppar')->default(false);
            $table->boolean('grandCounty')->default(false);
            $table->boolean('ires')->default(false);
            $table->text('mlsPrivateRemarks')->nullable();
            $table->text('mlsPublicRemarks')->nullable();
            $table->string('feesCharged')->nullable();
            $table->string('referralToPay')->nullable();
            $table->decimal('amountToCHR', 10, 2)->nullable();
            $table->text('referralDetails')->nullable();
            $table->boolean('matterport')->default(false);
            $table->boolean('floorPlans')->default(false);
            $table->boolean('threeDZillowTour')->default(false);
            $table->boolean('onsiteVideo')->default(false);
            $table->boolean('propertyWebsite')->default(false);
            $table->boolean('emailBlastSphere')->default(false);
            $table->boolean('emailBlastReverseProspect')->default(false);
            $table->boolean('propertyHighlightVideo')->default(false);
            $table->boolean('socialMediaImages')->default(false);
            $table->boolean('socialMediaAds')->default(false);
            $table->boolean('priceImprovementPackage')->default(false);
            $table->string('customDomainName')->nullable();
            $table->text('featuresNeededForVideo')->nullable();
            $table->text('marketingNotes')->nullable();
            $table->string('brochureLine')->nullable();
            $table->string('brochurePrint')->nullable();
            $table->text('bullets')->nullable();
            $table->string('headlineForBrochure')->nullable();
            $table->string('stickyDots')->nullable();
            $table->string('qrCodeSheet')->nullable();
            $table->boolean('qrCodeSignRider')->default(false);
            $table->string('featureCards')->nullable();
            $table->string('featureCardCopy')->nullable();
            $table->date('brochureDeliveryDate')->nullable();
            $table->string('deliveryAddress')->nullable();
            $table->date('printedItemsPickupDate')->nullable();
            $table->date('brochurePickupDate')->nullable();
            $table->boolean('isSubmittalComplete')->default(false);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('submittals', function (Blueprint $table) {
            $table->dropColumn([
                'transactionName',
                'additionalEmail',
                'agentName',
                'commingSoon',
                'comingSoonDate',
                'tmName',
                'activeDate',
                'agreementExecuted',
                'price',
                'photoDate',
                'photoURL',
                'bedsBathsTotal',
                'tourURL',
                'usingCHR',
                'needOE',
                'hasHOA',
                'includeInsights',
                'titleToOrderHOA',
                'mailoutNeeded',
                'powerOfAttnyNeeded',
                'hoaName',
                'hoaPhone',
                'hoaWebsite',
                'miscNotes',
                'scheduleSignInstall',
                'conciergeListing',
                'signInstallVendor',
                'draftShowingInstructions',
                'titleCompany',
                'closerNamePhone',
                'signInstallVendorOther',
                'signInstallDate',
                'reColorado',
                'navica',
                'ppar',
                'grandCounty',
                'ires',
                'mlsPrivateRemarks',
                'mlsPublicRemarks',
                'feesCharged',
                'referralToPay',
                'amountToCHR',
                'referralDetails',
                'matterport',
                'floorPlans',
                'threeDZillowTour',
                'onsiteVideo',
                'propertyWebsite',
                'emailBlastSphere',
                'emailBlastReverseProspect',
                'propertyHighlightVideo',
                'socialMediaImages',
                'socialMediaAds',
                'priceImprovementPackage',
                'customDomainName',
                'featuresNeededForVideo',
                'marketingNotes',
                'brochureLine',
                'brochurePrint',
                'bullets',
                'headlineForBrochure',
                'stickyDots',
                'qrCodeSheet',
                'qrCodeSignRider',
                'featureCards',
                'featureCardCopy',
                'brochureDeliveryDate',
                'deliveryAddress',
                'printedItemsPickupDate',
                'brochurePickupDate',
            ]);
        });
    }
};